# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: WinUtilities.WinUtilitiesSuite
PackageVersion: 1.2.0
ManifestType: version
ManifestVersion: 1.6.0
