import { JunkCategory, RegistryIssue, StartupItem } from './types';

export const INITIAL_JUNK_CATEGORIES: JunkCategory[] = [
  {
    id: 'sys_cache',
    name: 'Windows System Cache',
    description: 'Temporary files created by system services, update leftovers, and hardware shaders.',
    sizeInMb: 824.5,
    selected: true,
    cleaned: false,
    files: [
      'C:\\Windows\\SoftwareDistribution\\Download\\update_p1208.cab (240 MB)',
      'C:\\Windows\\Prefetch\\EXPLORER.EXE-3A7F112.pf (8.2 MB)',
      'C:\\ProgramData\\Microsoft\\ShaderCache\\D3D12_Cache.bin (180.3 MB)',
      'C:\\Windows\\Temp\\~DF3810A110.tmp (385 MB)',
      'C:\\Windows\\Logs\\CBS\\CBS.log (11 MB)'
    ]
  },
  {
    id: 'user_temp',
    name: 'Temporary App Files',
    description: 'Local temporary folders generated by web browsers, desktop apps, and system processes.',
    sizeInMb: 1243.2,
    selected: true,
    cleaned: false,
    files: [
      'C:\\Users\\Admin\\AppData\\Local\\Temp\\chrome_render_cache_01.tmp (512 MB)',
      'C:\\Users\\Admin\\AppData\\Local\\Temp\\figma_image_draft.cache (320 MB)',
      'C:\\Users\\Admin\\AppData\\Local\\Temp\\vscode-cpp-tools.sqlite (411.2 MB)',
      'C:\\Users\\Admin\\AppData\\Roaming\\Spotify\\Data\\index.db (0.01 MB)'
    ]
  },
  {
    id: 'empty_logs',
    name: 'System Error & Telemetry Logs',
    description: 'Diagnostic log collections, error dumps, and administrative records.',
    sizeInMb: 142.0,
    selected: false,
    cleaned: false,
    files: [
      'C:\\Windows\\System32\\winevt\\Logs\\Telemetry_Diagnostic_Record.evtx (85 MB)',
      'C:\\Windows\\INF\\setupapi.dev.log (12.5 MB)',
      'C:\\ProgramData\\Microsoft\\Windows\\WER\\ReportArchive\\\x00_crash.dmp (44.5 MB)'
    ]
  },
  {
    id: 'browser_cookies',
    name: 'Browser History & Cache',
    description: 'Cached websites, offline thumbnails, and analytical tracker stores.',
    sizeInMb: 412.8,
    selected: true,
    cleaned: false,
    files: [
      'C:\\Users\\Admin\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Cache\\data_2 (210 MB)',
      'C:\\Users\\Admin\\AppData\\Local\\Mozilla\\Firefox\\Profiles\\site_thumbnails\\index.dat (102.8 MB)',
      'C:\\Users\\Admin\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Storage\\index.db (100 MB)'
    ]
  },
  {
    id: 'download_setups',
    name: 'Downloaded Installer Residues',
    description: 'Archive backups of previously finished installations, MSI loaders, and installers.',
    sizeInMb: 2315.0,
    selected: true,
    cleaned: false,
    files: [
      'C:\\Users\\Admin\\Downloads\\node-v20.x-x64.msi (32.5 MB)',
      'C:\\Users\\Admin\\Downloads\\Git-2.43.0-64-bit.exe (58 MB)',
      'C:\\Users\\Admin\\Downloads\\Docker-Desktop-Installer.exe (612 MB)',
      'C:\\Users\\Admin\\Downloads\\Postgres_Installer_v16.exe (350 MB)',
      'C:\\Users\\Admin\\Downloads\\Blender_Release_v4.1.msi (1262.5 MB)'
    ]
  },
  {
    id: 'recycle_bin',
    name: 'Windows Recycle Bin',
    description: 'Deleted folders, drafts, and duplicate documents currently sitting in the trash.',
    sizeInMb: 1890.1,
    selected: true,
    cleaned: false,
    files: [
      'C:\\$Recycle.Bin\\S-1-5-21-28519\\$R19A82D.psd (450 MB)',
      'C:\\$Recycle.Bin\\S-1-5-21-28519\\$R828A18_video.mov (1340.1 MB)',
      'C:\\$Recycle.Bin\\S-1-5-21-28519\\$R92019A_archive.zip (100 MB)'
    ]
  }
];

export const INITIAL_REGISTRY_ISSUES: RegistryIssue[] = [
  {
    id: 'reg_01',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\.tmp',
    issue: 'Invalid open-with command pointing to a missing or deleted program: notepad.old.exe',
    severity: 'medium',
    selected: true,
    fixed: false
  },
  {
    id: 'reg_02',
    hive: 'HKEY_CLASSES_ROOT',
    path: 'CLSID\\{A84F-918B-E3C5-911E}\\InProcServer32',
    issue: 'Orphaned shared DLL reference: C:\\Windows\\System32\\comctl32.bak.dll does not exist.',
    severity: 'high',
    selected: true,
    fixed: false
  },
  {
    id: 'reg_03',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'Software\\Microsoft\\Windows\\Help\\SupportCatalog',
    issue: 'Invalid help file file-path: refers to missing manual file c:\\windows\\help\\v16_guide.chm',
    severity: 'low',
    selected: false,
    fixed: false
  },
  {
    id: 'reg_04',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Microsoft\\ActiveMovie\\decommissioned_player',
    issue: 'Stale Active X control binding referencing missing COM server codec bundle pack.',
    severity: 'medium',
    selected: true,
    fixed: false
  },
  {
    id: 'reg_05',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\LegacyUtility',
    issue: 'Dangling application reference. Application has already been deleted but uninstall registry persists.',
    severity: 'high',
    selected: true,
    fixed: false
  },
  {
    id: 'reg_06',
    hive: 'HKEY_LOCAL_MACHINE',
    path: 'Software\\Microsoft\\Windows\\CurrentVersion\\Run\\DanglingLauncher',
    issue: 'Startup shortcut registry entry points to an invalid path: C:\\Program Files\\Helper\\start.exe',
    severity: 'high',
    selected: true,
    fixed: false
  },
  {
    id: 'reg_07',
    hive: 'HKEY_CURRENT_USER',
    path: 'Software\\Classes\\TypeLib\\{883C-1F0A-BC82-9901}',
    issue: 'Missing dynamic library binding reference in internal interface class wrapper catalog.',
    severity: 'low',
    selected: true,
    fixed: false
  }
];

export const INITIAL_STARTUP_ITEMS: StartupItem[] = [
  {
    id: 'start_01',
    name: 'Microsoft OneDrive',
    publisher: 'Microsoft Corporation',
    impact: 'medium',
    enabled: true,
    path: 'C:\\Users\\Admin\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe'
  },
  {
    id: 'start_02',
    name: 'Discord Update Agent',
    publisher: 'Discord Inc.',
    impact: 'high',
    enabled: true,
    path: 'C:\\Users\\Admin\\AppData\\Local\\Discord\\Update.exe'
  },
  {
    id: 'start_03',
    name: 'Steam Client Bootstrapper',
    publisher: 'Valve Corporation',
    impact: 'high',
    enabled: false,
    path: 'C:\\Program Files (x86)\\Steam\\steam.exe'
  },
  {
    id: 'start_04',
    name: 'Spotify Web Helper',
    publisher: 'Spotify',
    impact: 'medium',
    enabled: true,
    path: 'C:\\Users\\Admin\\AppData\\Roaming\\Spotify\\SpotifyWebHelper.exe'
  },
  {
    id: 'start_05',
    name: 'Adobe Creative Cloud',
    publisher: 'Adobe Inc.',
    impact: 'high',
    enabled: true,
    path: 'C:\\Program Files (x86)\\Common Files\\Adobe\\OOBE\\PDApp\\core\\CC.exe'
  },
  {
    id: 'start_06',
    name: 'Java Update Scheduler',
    publisher: 'Oracle Corporation',
    impact: 'low',
    enabled: false,
    path: 'C:\\Program Files (x86)\\Common Files\\Java\\Java Update\\jusched.exe'
  },
  {
    id: 'start_07',
    name: 'Windows Security Systray',
    publisher: 'Microsoft Corporation',
    impact: 'low',
    enabled: true,
    path: 'C:\\Windows\\System32\\SecurityHealthSystray.exe'
  }
];
